# docker-compose up
# docker-compose down
version: '3'
services:
  # https://hub.docker.com/r/library/redis/
  redis:
    image: redis:3.2
    # environment:
    ports:
      - "6379:6379" # guest host
